[pytest]
asyncio_mode = auto
pythonpath = app/
norecursedirs = env/*
addopts = -p no:cacheprovider
testpaths = tests/
python_files = test_*.py
filterwarnings =
    ignore:datetime\.datetime\.utcnow\(\) is deprecated:DeprecationWarning:freezegun\.api
    ignore:coroutine 'AsyncSession\.commit' was never awaited:RuntimeWarning:mixer\.backend\.sqlalchemy
