"""Константы приложения QRKot."""

MIN_PROJECT_NAME_LENGTH = 5
MAX_PROJECT_NAME_LENGTH = 100
MIN_PROJECT_DESCRIPTION_LENGTH = 10

MIN_PASSWORD_LENGTH = 3
JWT_LIFETIME_SECONDS = 3600

PASSWORD_LENGTH_ERROR = (
    f'Password should be at least {MIN_PASSWORD_LENGTH} characters'
)
